source 'http://rubygems.org'

gem 'rails', '3.1.0'
gem 'sqlite3'
gem 'json'

group :assets do
  gem 'sass-rails', "  ~> 3.1.0"
  gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'
end

gem 'jquery-rails'
gem 'unicorn'
gem 'ruby-debug'

